#!/bin/bash

set -ex

cip exec cpanm Devel::Hide
cip sudo dzil-cpanm Dist::Zilla::Plugin::OurPkgVersion

if [ ! -z "$PERL_CRITIC" ]; then
    cip exec cpanm -v -n Perl::Critic Perl::Critic::Freenode https://dist.wdlabs.com/Test2-Tools-PerlCritic-0.01.tar.gz
fi
